name: Update Submodules
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  actions: read

jobs:
  Update-Submodules:
    if: ${{ github.repository == 'CHTC/chtc-website-source' }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Pull down submodules
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git submodule update --init --recursive --remote
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update Article Submodule"
            git push
            echo "build=true" >> "$GITHUB_OUTPUT"
          else
            echo "no changes";
            echo "build=false" >> "$GITHUB_OUTPUT"
          fi

  build-updated-website:
    needs: [Update-Submodules]
    if: ${{ needs.Update-Submodules.outputs.build == 'true' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit